# Generated by Django 4.1 on 2023-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RGroupLabel',
            fields=[
                ('label', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField()),
                ('rgroup_labels', models.ManyToManyField(to='api.rgrouplabel')),
            ],
        ),
    ]
